//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeePeek.Client.App.Resources.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CoffeePeek.Client.App.Resources.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LoginPage_LoginButton {
            get {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }
        
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        public static string LoginPage_Subtitle {
            get {
                return ResourceManager.GetString("LoginPage_Subtitle", resourceCulture);
            }
        }
        
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static string WelcomePage_Slogan {
            get {
                return ResourceManager.GetString("WelcomePage_Slogan", resourceCulture);
            }
        }
        
        public static string WelcomePage_MainTitle {
            get {
                return ResourceManager.GetString("WelcomePage_MainTitle", resourceCulture);
            }
        }
        
        public static string WelcomePage_MainDescription {
            get {
                return ResourceManager.GetString("WelcomePage_MainDescription", resourceCulture);
            }
        }
        
        public static string RegisterPage_RegisterButton {
            get {
                return ResourceManager.GetString("RegisterPage_RegisterButton", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card1Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card1Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card2Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card2Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card3Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card3Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card4Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card4Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card5Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card5Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card6Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card6Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card1Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card1Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card2Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card2Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card3Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card3Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card4Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card4Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card5Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card5Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card6Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card6Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Footer {
            get {
                return ResourceManager.GetString("WelcomePage_Footer", resourceCulture);
            }
        }
        
        public static string Auth_FillAllFields {
            get {
                return ResourceManager.GetString("Auth_FillAllFields", resourceCulture);
            }
        }
        
        public static string Auth_LoginFailed {
            get {
                return ResourceManager.GetString("Auth_LoginFailed", resourceCulture);
            }
        }
        
        public static string Auth_InvalidEmail {
            get {
                return ResourceManager.GetString("Auth_InvalidEmail", resourceCulture);
            }
        }
        
        public static string Auth_EmailCheckFailed {
            get {
                return ResourceManager.GetString("Auth_EmailCheckFailed", resourceCulture);
            }
        }
        
        public static string Auth_PasswordMismatch {
            get {
                return ResourceManager.GetString("Auth_PasswordMismatch", resourceCulture);
            }
        }
        
        public static string Auth_RegisterFailed {
            get {
                return ResourceManager.GetString("Auth_RegisterFailed", resourceCulture);
            }
        }
        
        public static string Auth_LoginAfterRegisterFailed {
            get {
                return ResourceManager.GetString("Auth_LoginAfterRegisterFailed", resourceCulture);
            }
        }
        
        public static string LoginPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string LoginPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        public static string RegisterPage_Title {
            get {
                return ResourceManager.GetString("RegisterPage_Title", resourceCulture);
            }
        }
        
        public static string RegisterPage_UserNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_UserNamePlaceholder", resourceCulture);
            }
        }
        
        public static string RegisterPage_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string Register_CheckEmailTitle {
            get {
                return ResourceManager.GetString("Register_CheckEmailTitle", resourceCulture);
            }
        }
        
        public static string Register_CheckEmailSubtitle {
            get {
                return ResourceManager.GetString("Register_CheckEmailSubtitle", resourceCulture);
            }
        }
        
        public static string Register_CompleteSubtitle {
            get {
                return ResourceManager.GetString("Register_CompleteSubtitle", resourceCulture);
            }
        }
        
        public static string Auth_NoAccount {
            get {
                return ResourceManager.GetString("Auth_NoAccount", resourceCulture);
            }
        }
        
        public static string Auth_CreateAccount {
            get {
                return ResourceManager.GetString("Auth_CreateAccount", resourceCulture);
            }
        }
        
        public static string Auth_HasAccount {
            get {
                return ResourceManager.GetString("Auth_HasAccount", resourceCulture);
            }
        }
        
        public static string Auth_SignIn {
            get {
                return ResourceManager.GetString("Auth_SignIn", resourceCulture);
            }
        }
        
        public static string Auth_ChangeEmail {
            get {
                return ResourceManager.GetString("Auth_ChangeEmail", resourceCulture);
            }
        }
        
        public static string Auth_LabelEmail {
            get {
                return ResourceManager.GetString("Auth_LabelEmail", resourceCulture);
            }
        }
        
        public static string Auth_LabelPassword {
            get {
                return ResourceManager.GetString("Auth_LabelPassword", resourceCulture);
            }
        }
        
        public static string Auth_LabelConfirmPassword {
            get {
                return ResourceManager.GetString("Auth_LabelConfirmPassword", resourceCulture);
            }
        }
        
        public static string Auth_LabelUserName {
            get {
                return ResourceManager.GetString("Auth_LabelUserName", resourceCulture);
            }
        }
        
        public static string Auth_PrivacyRequired {
            get {
                return ResourceManager.GetString("Auth_PrivacyRequired", resourceCulture);
            }
        }
        
        public static string Auth_PrivacyConsent {
            get {
                return ResourceManager.GetString("Auth_PrivacyConsent", resourceCulture);
            }
        }
        
        public static string Auth_PasswordMinLength {
            get {
                return ResourceManager.GetString("Auth_PasswordMinLength", resourceCulture);
            }
        }
        
        public static string Auth_ThemeToggle {
            get {
                return ResourceManager.GetString("Auth_ThemeToggle", resourceCulture);
            }
        }
        
        public static string Auth_BrandCoffee {
            get {
                return ResourceManager.GetString("Auth_BrandCoffee", resourceCulture);
            }
        }
        
        public static string Auth_BrandPeek {
            get {
                return ResourceManager.GetString("Auth_BrandPeek", resourceCulture);
            }
        }
        
        public static string Register_Continue {
            get {
                return ResourceManager.GetString("Register_Continue", resourceCulture);
            }
        }
        
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        public static string Home_SignOut {
            get {
                return ResourceManager.GetString("Home_SignOut", resourceCulture);
            }
        }
        
        public static string Header_Shops {
            get {
                return ResourceManager.GetString("Header_Shops", resourceCulture);
            }
        }
        
        public static string Header_Map {
            get {
                return ResourceManager.GetString("Header_Map", resourceCulture);
            }
        }
        
        public static string ShopPage_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ShopPage_SearchPlaceholder", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter {
            get {
                return ResourceManager.GetString("ShopPage_Filter", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_City {
            get {
                return ResourceManager.GetString("ShopPage_Filter_City", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_OpenTime {
            get {
                return ResourceManager.GetString("ShopPage_Filter_OpenTime", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_New {
            get {
                return ResourceManager.GetString("ShopPage_Filter_New", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_Favorite {
            get {
                return ResourceManager.GetString("ShopPage_Filter_Favorite", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_Visited {
            get {
                return ResourceManager.GetString("ShopPage_Filter_Visited", resourceCulture);
            }
        }
        
        public static string ShopPage_CityPopupTitle {
            get {
                return ResourceManager.GetString("ShopPage_CityPopupTitle", resourceCulture);
            }
        }
        
        public static string ShopPage_AdditionalFiltersHint {
            get {
                return ResourceManager.GetString("ShopPage_AdditionalFiltersHint", resourceCulture);
            }
        }
        
        public static string ShopPage_Trending {
            get {
                return ResourceManager.GetString("ShopPage_Trending", resourceCulture);
            }
        }
        
        public static string Profile_ThemeToggle {
            get {
                return ResourceManager.GetString("Profile_ThemeToggle", resourceCulture);
            }
        }
        
        public static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        public static string Profile_Loading {
            get {
                return ResourceManager.GetString("Profile_Loading", resourceCulture);
            }
        }
        
        public static string Profile_LoadError {
            get {
                return ResourceManager.GetString("Profile_LoadError", resourceCulture);
            }
        }
        
        public static string Profile_MemberSince {
            get {
                return ResourceManager.GetString("Profile_MemberSince", resourceCulture);
            }
        }
        
        public static string Profile_StatCheckIns {
            get {
                return ResourceManager.GetString("Profile_StatCheckIns", resourceCulture);
            }
        }
        
        public static string Profile_StatReviews {
            get {
                return ResourceManager.GetString("Profile_StatReviews", resourceCulture);
            }
        }
        
        public static string Profile_StatRating {
            get {
                return ResourceManager.GetString("Profile_StatRating", resourceCulture);
            }
        }
        
        public static string Profile_LastReviews {
            get {
                return ResourceManager.GetString("Profile_LastReviews", resourceCulture);
            }
        }
        
        public static string Profile_ReviewsTotal {
            get {
                return ResourceManager.GetString("Profile_ReviewsTotal", resourceCulture);
            }
        }
        
        public static string Profile_NoReviewsYet {
            get {
                return ResourceManager.GetString("Profile_NoReviewsYet", resourceCulture);
            }
        }
        
        public static string Profile_NoReviews {
            get {
                return ResourceManager.GetString("Profile_NoReviews", resourceCulture);
            }
        }
        
        public static string Profile_GoToShop {
            get {
                return ResourceManager.GetString("Profile_GoToShop", resourceCulture);
            }
        }
        
        public static string Profile_PreviousPage {
            get {
                return ResourceManager.GetString("Profile_PreviousPage", resourceCulture);
            }
        }
        
        public static string Profile_NextPage {
            get {
                return ResourceManager.GetString("Profile_NextPage", resourceCulture);
            }
        }
        
        public static string Profile_PageOf {
            get {
                return ResourceManager.GetString("Profile_PageOf", resourceCulture);
            }
        }
        
        public static string Profile_ReviewDefaultTitle {
            get {
                return ResourceManager.GetString("Profile_ReviewDefaultTitle", resourceCulture);
            }
        }
        
        public static string ShopPage_LoadError {
            get {
                return ResourceManager.GetString("ShopPage_LoadError", resourceCulture);
            }
        }
        
        public static string ShopPage_LoadMore {
            get {
                return ResourceManager.GetString("ShopPage_LoadMore", resourceCulture);
            }
        }
        
        public static string ShopDetail_LoadError {
            get {
                return ResourceManager.GetString("ShopDetail_LoadError", resourceCulture);
            }
        }
        
        public static string ShopDetail_Schedule {
            get {
                return ResourceManager.GetString("ShopDetail_Schedule", resourceCulture);
            }
        }
        
        public static string ShopDetail_Contact {
            get {
                return ResourceManager.GetString("ShopDetail_Contact", resourceCulture);
            }
        }
        
        public static string ShopDetail_Reviews {
            get {
                return ResourceManager.GetString("ShopDetail_Reviews", resourceCulture);
            }
        }
        
        public static string ShopDetail_Open {
            get {
                return ResourceManager.GetString("ShopDetail_Open", resourceCulture);
            }
        }
    }
}
