//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeePeek.Client.App.Resources.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CoffeePeek.Client.App.Resources.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LoginPage_LoginButton {
            get {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }
        
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        public static string LoginPage_Subtitle {
            get {
                return ResourceManager.GetString("LoginPage_Subtitle", resourceCulture);
            }
        }
        
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static string WelcomePage_Slogan {
            get {
                return ResourceManager.GetString("WelcomePage_Slogan", resourceCulture);
            }
        }
        
        public static string WelcomePage_MainTitle {
            get {
                return ResourceManager.GetString("WelcomePage_MainTitle", resourceCulture);
            }
        }
        
        public static string WelcomePage_MainDescription {
            get {
                return ResourceManager.GetString("WelcomePage_MainDescription", resourceCulture);
            }
        }
        
        public static string RegisterPage_RegisterButton {
            get {
                return ResourceManager.GetString("RegisterPage_RegisterButton", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card1Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card1Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card2Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card2Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card3Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card3Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card4Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card4Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card5Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card5Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card6Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card6Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card1Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card1Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card2Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card2Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card3Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card3Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card4Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card4Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card5Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card5Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card6Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card6Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Footer {
            get {
                return ResourceManager.GetString("WelcomePage_Footer", resourceCulture);
            }
        }
        
        public static string Auth_FillAllFields {
            get {
                return ResourceManager.GetString("Auth_FillAllFields", resourceCulture);
            }
        }
        
        public static string Auth_LoginFailed {
            get {
                return ResourceManager.GetString("Auth_LoginFailed", resourceCulture);
            }
        }
        
        public static string Auth_InvalidEmail {
            get {
                return ResourceManager.GetString("Auth_InvalidEmail", resourceCulture);
            }
        }
        
        public static string Auth_EmailCheckFailed {
            get {
                return ResourceManager.GetString("Auth_EmailCheckFailed", resourceCulture);
            }
        }
        
        public static string Auth_PasswordMismatch {
            get {
                return ResourceManager.GetString("Auth_PasswordMismatch", resourceCulture);
            }
        }
        
        public static string Auth_RegisterFailed {
            get {
                return ResourceManager.GetString("Auth_RegisterFailed", resourceCulture);
            }
        }
        
        public static string Auth_LoginAfterRegisterFailed {
            get {
                return ResourceManager.GetString("Auth_LoginAfterRegisterFailed", resourceCulture);
            }
        }
        
        public static string LoginPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string LoginPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        public static string RegisterPage_Title {
            get {
                return ResourceManager.GetString("RegisterPage_Title", resourceCulture);
            }
        }
        
        public static string RegisterPage_UserNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_UserNamePlaceholder", resourceCulture);
            }
        }
        
        public static string RegisterPage_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string Register_CheckEmailTitle {
            get {
                return ResourceManager.GetString("Register_CheckEmailTitle", resourceCulture);
            }
        }
        
        public static string Register_CheckEmailSubtitle {
            get {
                return ResourceManager.GetString("Register_CheckEmailSubtitle", resourceCulture);
            }
        }
        
        public static string Register_CompleteSubtitle {
            get {
                return ResourceManager.GetString("Register_CompleteSubtitle", resourceCulture);
            }
        }
        
        public static string Auth_NoAccount {
            get {
                return ResourceManager.GetString("Auth_NoAccount", resourceCulture);
            }
        }
        
        public static string Auth_CreateAccount {
            get {
                return ResourceManager.GetString("Auth_CreateAccount", resourceCulture);
            }
        }
        
        public static string Auth_HasAccount {
            get {
                return ResourceManager.GetString("Auth_HasAccount", resourceCulture);
            }
        }
        
        public static string Auth_SignIn {
            get {
                return ResourceManager.GetString("Auth_SignIn", resourceCulture);
            }
        }
        
        public static string Auth_ChangeEmail {
            get {
                return ResourceManager.GetString("Auth_ChangeEmail", resourceCulture);
            }
        }
        
        public static string Auth_LabelEmail {
            get {
                return ResourceManager.GetString("Auth_LabelEmail", resourceCulture);
            }
        }
        
        public static string Auth_LabelPassword {
            get {
                return ResourceManager.GetString("Auth_LabelPassword", resourceCulture);
            }
        }
        
        public static string Auth_LabelConfirmPassword {
            get {
                return ResourceManager.GetString("Auth_LabelConfirmPassword", resourceCulture);
            }
        }
        
        public static string Auth_LabelUserName {
            get {
                return ResourceManager.GetString("Auth_LabelUserName", resourceCulture);
            }
        }
        
        public static string Auth_PrivacyRequired {
            get {
                return ResourceManager.GetString("Auth_PrivacyRequired", resourceCulture);
            }
        }
        
        public static string Auth_PrivacyConsent {
            get {
                return ResourceManager.GetString("Auth_PrivacyConsent", resourceCulture);
            }
        }
        
        public static string Auth_PasswordMinLength {
            get {
                return ResourceManager.GetString("Auth_PasswordMinLength", resourceCulture);
            }
        }
        
        public static string Auth_ThemeToggle {
            get {
                return ResourceManager.GetString("Auth_ThemeToggle", resourceCulture);
            }
        }
        
        public static string Auth_BrandCoffee {
            get {
                return ResourceManager.GetString("Auth_BrandCoffee", resourceCulture);
            }
        }
        
        public static string Auth_BrandPeek {
            get {
                return ResourceManager.GetString("Auth_BrandPeek", resourceCulture);
            }
        }
        
        public static string Register_Continue {
            get {
                return ResourceManager.GetString("Register_Continue", resourceCulture);
            }
        }
        
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        public static string Home_SignOut {
            get {
                return ResourceManager.GetString("Home_SignOut", resourceCulture);
            }
        }
        
        public static string Header_Shops {
            get {
                return ResourceManager.GetString("Header_Shops", resourceCulture);
            }
        }
        
        public static string Header_Map {
            get {
                return ResourceManager.GetString("Header_Map", resourceCulture);
            }
        }
        
        public static string Header_Moderation {
            get {
                return ResourceManager.GetString("Header_Moderation", resourceCulture);
            }
        }
        
        public static string Moderation_Title {
            get {
                return ResourceManager.GetString("Moderation_Title", resourceCulture);
            }
        }
        
        public static string Moderation_Subtitle {
            get {
                return ResourceManager.GetString("Moderation_Subtitle", resourceCulture);
            }
        }
        
        public static string Moderation_Refresh {
            get {
                return ResourceManager.GetString("Moderation_Refresh", resourceCulture);
            }
        }
        
        public static string Moderation_Close {
            get {
                return ResourceManager.GetString("Moderation_Close", resourceCulture);
            }
        }
        
        public static string Moderation_SectionShops {
            get {
                return ResourceManager.GetString("Moderation_SectionShops", resourceCulture);
            }
        }
        
        public static string Moderation_SectionReviews {
            get {
                return ResourceManager.GetString("Moderation_SectionReviews", resourceCulture);
            }
        }
        
        public static string Moderation_Approve {
            get {
                return ResourceManager.GetString("Moderation_Approve", resourceCulture);
            }
        }
        
        public static string Moderation_Reject {
            get {
                return ResourceManager.GetString("Moderation_Reject", resourceCulture);
            }
        }
        
        public static string Moderation_RejectReasonPlaceholder {
            get {
                return ResourceManager.GetString("Moderation_RejectReasonPlaceholder", resourceCulture);
            }
        }
        
        public static string Moderation_LoadError {
            get {
                return ResourceManager.GetString("Moderation_LoadError", resourceCulture);
            }
        }
        
        public static string Moderation_ActionFailed {
            get {
                return ResourceManager.GetString("Moderation_ActionFailed", resourceCulture);
            }
        }
        
        public static string Moderation_DefaultRejectReason {
            get {
                return ResourceManager.GetString("Moderation_DefaultRejectReason", resourceCulture);
            }
        }
        
        public static string Moderation_EmptyShops {
            get {
                return ResourceManager.GetString("Moderation_EmptyShops", resourceCulture);
            }
        }
        
        public static string Moderation_EmptyReviews {
            get {
                return ResourceManager.GetString("Moderation_EmptyReviews", resourceCulture);
            }
        }
        
        public static string Moderation_Loading {
            get {
                return ResourceManager.GetString("Moderation_Loading", resourceCulture);
            }
        }
        
        public static string ShopPage_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ShopPage_SearchPlaceholder", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter {
            get {
                return ResourceManager.GetString("ShopPage_Filter", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_City {
            get {
                return ResourceManager.GetString("ShopPage_Filter_City", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_OpenTime {
            get {
                return ResourceManager.GetString("ShopPage_Filter_OpenTime", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_New {
            get {
                return ResourceManager.GetString("ShopPage_Filter_New", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_Favorite {
            get {
                return ResourceManager.GetString("ShopPage_Filter_Favorite", resourceCulture);
            }
        }
        
        public static string ShopPage_Filter_Visited {
            get {
                return ResourceManager.GetString("ShopPage_Filter_Visited", resourceCulture);
            }
        }
        
        public static string ShopPage_CityPopupTitle {
            get {
                return ResourceManager.GetString("ShopPage_CityPopupTitle", resourceCulture);
            }
        }
        
        public static string ShopPage_AdditionalFiltersHint {
            get {
                return ResourceManager.GetString("ShopPage_AdditionalFiltersHint", resourceCulture);
            }
        }
        
        public static string ShopPage_Trending {
            get {
                return ResourceManager.GetString("ShopPage_Trending", resourceCulture);
            }
        }
        
        public static string Profile_ThemeToggle {
            get {
                return ResourceManager.GetString("Profile_ThemeToggle", resourceCulture);
            }
        }
        
        public static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        public static string Profile_Loading {
            get {
                return ResourceManager.GetString("Profile_Loading", resourceCulture);
            }
        }
        
        public static string Profile_LoadError {
            get {
                return ResourceManager.GetString("Profile_LoadError", resourceCulture);
            }
        }
        
        public static string Profile_MemberSince {
            get {
                return ResourceManager.GetString("Profile_MemberSince", resourceCulture);
            }
        }
        
        public static string Profile_StatCheckIns {
            get {
                return ResourceManager.GetString("Profile_StatCheckIns", resourceCulture);
            }
        }
        
        public static string Profile_StatReviews {
            get {
                return ResourceManager.GetString("Profile_StatReviews", resourceCulture);
            }
        }
        
        public static string Profile_StatRating {
            get {
                return ResourceManager.GetString("Profile_StatRating", resourceCulture);
            }
        }
        
        public static string Profile_LastReviews {
            get {
                return ResourceManager.GetString("Profile_LastReviews", resourceCulture);
            }
        }
        
        public static string Profile_ReviewsTotal {
            get {
                return ResourceManager.GetString("Profile_ReviewsTotal", resourceCulture);
            }
        }
        
        public static string Profile_NoReviewsYet {
            get {
                return ResourceManager.GetString("Profile_NoReviewsYet", resourceCulture);
            }
        }
        
        public static string Profile_NoReviews {
            get {
                return ResourceManager.GetString("Profile_NoReviews", resourceCulture);
            }
        }
        
        public static string Profile_GoToShop {
            get {
                return ResourceManager.GetString("Profile_GoToShop", resourceCulture);
            }
        }
        
        public static string Profile_PreviousPage {
            get {
                return ResourceManager.GetString("Profile_PreviousPage", resourceCulture);
            }
        }
        
        public static string Profile_NextPage {
            get {
                return ResourceManager.GetString("Profile_NextPage", resourceCulture);
            }
        }
        
        public static string Profile_PageOf {
            get {
                return ResourceManager.GetString("Profile_PageOf", resourceCulture);
            }
        }
        
        public static string Profile_ReviewDefaultTitle {
            get {
                return ResourceManager.GetString("Profile_ReviewDefaultTitle", resourceCulture);
            }
        }
        
        public static string ShopPage_LoadError {
            get {
                return ResourceManager.GetString("ShopPage_LoadError", resourceCulture);
            }
        }
        
        public static string ShopPage_LoadMore {
            get {
                return ResourceManager.GetString("ShopPage_LoadMore", resourceCulture);
            }
        }
        
        public static string ShopDetail_LoadError {
            get {
                return ResourceManager.GetString("ShopDetail_LoadError", resourceCulture);
            }
        }
        
        public static string ShopDetail_Schedule {
            get {
                return ResourceManager.GetString("ShopDetail_Schedule", resourceCulture);
            }
        }
        
        public static string ShopDetail_Contact {
            get {
                return ResourceManager.GetString("ShopDetail_Contact", resourceCulture);
            }
        }
        
        public static string ShopDetail_Reviews {
            get {
                return ResourceManager.GetString("ShopDetail_Reviews", resourceCulture);
            }
        }
        
        public static string ShopDetail_Open {
            get {
                return ResourceManager.GetString("ShopDetail_Open", resourceCulture);
            }
        }
        
        public static string Profile_Edit {
            get {
                return ResourceManager.GetString("Profile_Edit", resourceCulture);
            }
        }
        
        public static string Profile_EditTitle {
            get {
                return ResourceManager.GetString("Profile_EditTitle", resourceCulture);
            }
        }
        
        public static string Profile_Edit_Username {
            get {
                return ResourceManager.GetString("Profile_Edit_Username", resourceCulture);
            }
        }
        
        public static string Profile_Edit_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Profile_Edit_UsernamePlaceholder", resourceCulture);
            }
        }
        
        public static string Profile_Edit_About {
            get {
                return ResourceManager.GetString("Profile_Edit_About", resourceCulture);
            }
        }
        
        public static string Profile_Edit_AboutPlaceholder {
            get {
                return ResourceManager.GetString("Profile_Edit_AboutPlaceholder", resourceCulture);
            }
        }
        
        public static string Profile_Edit_Save {
            get {
                return ResourceManager.GetString("Profile_Edit_Save", resourceCulture);
            }
        }
        
        public static string Profile_Edit_Cancel {
            get {
                return ResourceManager.GetString("Profile_Edit_Cancel", resourceCulture);
            }
        }
        
        public static string Profile_Edit_SaveError {
            get {
                return ResourceManager.GetString("Profile_Edit_SaveError", resourceCulture);
            }
        }
        
        public static string Profile_Edit_UsernameRequired {
            get {
                return ResourceManager.GetString("Profile_Edit_UsernameRequired", resourceCulture);
            }
        }

        public static string Profile_AvatarUpload {
            get {
                return ResourceManager.GetString("Profile_AvatarUpload", resourceCulture);
            }
        }

        public static string Profile_AvatarUploadError {
            get {
                return ResourceManager.GetString("Profile_AvatarUploadError", resourceCulture);
            }
        }

        public static string ShopPage_FilterBeans {
            get {
                return ResourceManager.GetString("ShopPage_FilterBeans", resourceCulture);
            }
        }

        public static string ShopPage_FilterRoasters {
            get {
                return ResourceManager.GetString("ShopPage_FilterRoasters", resourceCulture);
            }
        }

        public static string ShopPage_FilterBrewMethods {
            get {
                return ResourceManager.GetString("ShopPage_FilterBrewMethods", resourceCulture);
            }
        }

        public static string ShopPage_FilterEquipment {
            get {
                return ResourceManager.GetString("ShopPage_FilterEquipment", resourceCulture);
            }
        }

        public static string ShopPage_FilterApply {
            get {
                return ResourceManager.GetString("ShopPage_FilterApply", resourceCulture);
            }
        }

        public static string ShopPage_FilterClear {
            get {
                return ResourceManager.GetString("ShopPage_FilterClear", resourceCulture);
            }
        }

        public static string ShopPage_SuggestShop {
            get {
                return ResourceManager.GetString("ShopPage_SuggestShop", resourceCulture);
            }
        }

        public static string SuggestShop_Title {
            get {
                return ResourceManager.GetString("SuggestShop_Title", resourceCulture);
            }
        }

        public static string SuggestShop_RequiredTitle {
            get {
                return ResourceManager.GetString("SuggestShop_RequiredTitle", resourceCulture);
            }
        }

        public static string SuggestShop_FieldName {
            get {
                return ResourceManager.GetString("SuggestShop_FieldName", resourceCulture);
            }
        }

        public static string SuggestShop_FieldAddress {
            get {
                return ResourceManager.GetString("SuggestShop_FieldAddress", resourceCulture);
            }
        }

        public static string SuggestShop_SectionAbout {
            get {
                return ResourceManager.GetString("SuggestShop_SectionAbout", resourceCulture);
            }
        }

        public static string SuggestShop_FieldDescription {
            get {
                return ResourceManager.GetString("SuggestShop_FieldDescription", resourceCulture);
            }
        }

        public static string SuggestShop_SectionContacts {
            get {
                return ResourceManager.GetString("SuggestShop_SectionContacts", resourceCulture);
            }
        }

        public static string SuggestShop_FieldPhone {
            get {
                return ResourceManager.GetString("SuggestShop_FieldPhone", resourceCulture);
            }
        }

        public static string SuggestShop_FieldEmail {
            get {
                return ResourceManager.GetString("SuggestShop_FieldEmail", resourceCulture);
            }
        }

        public static string SuggestShop_FieldWebsite {
            get {
                return ResourceManager.GetString("SuggestShop_FieldWebsite", resourceCulture);
            }
        }

        public static string SuggestShop_FieldInstagram {
            get {
                return ResourceManager.GetString("SuggestShop_FieldInstagram", resourceCulture);
            }
        }

        public static string SuggestShop_SectionSchedule {
            get {
                return ResourceManager.GetString("SuggestShop_SectionSchedule", resourceCulture);
            }
        }

        public static string SuggestShop_FieldOpenTime {
            get {
                return ResourceManager.GetString("SuggestShop_FieldOpenTime", resourceCulture);
            }
        }

        public static string SuggestShop_FieldCloseTime {
            get {
                return ResourceManager.GetString("SuggestShop_FieldCloseTime", resourceCulture);
            }
        }

        public static string SuggestShop_FieldClosed {
            get {
                return ResourceManager.GetString("SuggestShop_FieldClosed", resourceCulture);
            }
        }

        public static string SuggestShop_SectionCoffeeProfile {
            get {
                return ResourceManager.GetString("SuggestShop_SectionCoffeeProfile", resourceCulture);
            }
        }

        public static string SuggestShop_SectionCoffeeBeans {
            get {
                return ResourceManager.GetString("SuggestShop_SectionCoffeeBeans", resourceCulture);
            }
        }

        public static string SuggestShop_SectionRoasters {
            get {
                return ResourceManager.GetString("SuggestShop_SectionRoasters", resourceCulture);
            }
        }

        public static string SuggestShop_SectionBrewMethods {
            get {
                return ResourceManager.GetString("SuggestShop_SectionBrewMethods", resourceCulture);
            }
        }

        public static string SuggestShop_SectionEquipment {
            get {
                return ResourceManager.GetString("SuggestShop_SectionEquipment", resourceCulture);
            }
        }

        public static string SuggestShop_SectionPhotos {
            get {
                return ResourceManager.GetString("SuggestShop_SectionPhotos", resourceCulture);
            }
        }

        public static string SuggestShop_AddPhoto {
            get {
                return ResourceManager.GetString("SuggestShop_AddPhoto", resourceCulture);
            }
        }

        public static string SuggestShop_RemovePhoto {
            get {
                return ResourceManager.GetString("SuggestShop_RemovePhoto", resourceCulture);
            }
        }

        public static string SuggestShop_Submit {
            get {
                return ResourceManager.GetString("SuggestShop_Submit", resourceCulture);
            }
        }

        public static string SuggestShop_ValidationRequired {
            get {
                return ResourceManager.GetString("SuggestShop_ValidationRequired", resourceCulture);
            }
        }

        public static string SuggestShop_SubmitError {
            get {
                return ResourceManager.GetString("SuggestShop_SubmitError", resourceCulture);
            }
        }

        public static string SuggestShop_SubmitSuccess {
            get {
                return ResourceManager.GetString("SuggestShop_SubmitSuccess", resourceCulture);
            }
        }

        public static string SuggestShop_DayMonday {
            get {
                return ResourceManager.GetString("SuggestShop_DayMonday", resourceCulture);
            }
        }

        public static string SuggestShop_DayTuesday {
            get {
                return ResourceManager.GetString("SuggestShop_DayTuesday", resourceCulture);
            }
        }

        public static string SuggestShop_DayWednesday {
            get {
                return ResourceManager.GetString("SuggestShop_DayWednesday", resourceCulture);
            }
        }

        public static string SuggestShop_DayThursday {
            get {
                return ResourceManager.GetString("SuggestShop_DayThursday", resourceCulture);
            }
        }

        public static string SuggestShop_DayFriday {
            get {
                return ResourceManager.GetString("SuggestShop_DayFriday", resourceCulture);
            }
        }

        public static string SuggestShop_DaySaturday {
            get {
                return ResourceManager.GetString("SuggestShop_DaySaturday", resourceCulture);
            }
        }

        public static string SuggestShop_DaySunday {
            get {
                return ResourceManager.GetString("SuggestShop_DaySunday", resourceCulture);
            }
        }
    }
}
