//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeePeek.Client.App.Resources.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CoffeePeek.Client.App.Resources.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LoginPage_LoginButton {
            get {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }
        
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static string WelcomePage_Slogan {
            get {
                return ResourceManager.GetString("WelcomePage_Slogan", resourceCulture);
            }
        }
        
        public static string WelcomePage_MainTitle {
            get {
                return ResourceManager.GetString("WelcomePage_MainTitle", resourceCulture);
            }
        }
        
        public static string WelcomePage_MainDescription {
            get {
                return ResourceManager.GetString("WelcomePage_MainDescription", resourceCulture);
            }
        }
        
        public static string RegisterPage_RegisterButton {
            get {
                return ResourceManager.GetString("RegisterPage_RegisterButton", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card1Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card1Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card2Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card2Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card3Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card3Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card4Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card4Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card5Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card5Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card6Title {
            get {
                return ResourceManager.GetString("WelcomePage_Card6Title", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card1Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card1Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card2Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card2Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card3Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card3Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card4Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card4Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card5Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card5Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Card6Description {
            get {
                return ResourceManager.GetString("WelcomePage_Card6Description", resourceCulture);
            }
        }
        
        public static string WelcomePage_Footer {
            get {
                return ResourceManager.GetString("WelcomePage_Footer", resourceCulture);
            }
        }
    }
}
