// <auto-generated />
using System;
using CoffeePeek.Moderation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeePeek.Moderation.Infrastructure.Migrations
{
    [DbContext(typeof(ModerationDbContext))]
    partial class ModerationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique();

                    b.ToTable("ModerationLocations");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationCoffeeBeanShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeBeanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeBeanId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationCoffeeBeanShops");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationRoasterShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoasterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoasterId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationRoasterShops");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAddressValidated")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ModerationShopContactId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotValidatedAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PriceRange")
                        .HasColumnType("integer");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ModerationShopContactId");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("UserId");

                    b.ToTable("ModerationShops");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopBrewMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewMethodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrewMethodId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationShopBrewMethods");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstagramLink")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ModerationShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModerationShopId1")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("SiteLink")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModerationShopId1");

                    b.ToTable("ModerationShopContacts");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationShopEquipments");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModerationShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModerationShopId");

                    b.ToTable("ModerationShopSchedules");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopScheduleInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("ModerationShopScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ModerationShopScheduleId");

                    b.ToTable("ModerationShopScheduleIntervals");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxEvents");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.PhotoMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModerationShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModerationShopId");

                    b.ToTable("ShopPhotos");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.Location", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", "ModerationShop")
                        .WithOne("Location")
                        .HasForeignKey("CoffeePeek.Moderation.Domain.Entities.Location", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationCoffeeBeanShop", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", "ModerationShop")
                        .WithMany("ModerationCoffeeBeanShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationRoasterShop", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", "ModerationShop")
                        .WithMany("ModerationRoasterShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShop", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShopContact", "ModerationShopContact")
                        .WithMany()
                        .HasForeignKey("ModerationShopContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModerationShopContact");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopBrewMethod", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", "ModerationShop")
                        .WithMany("ModerationShopBrewMethods")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopContact", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", "ModerationShop")
                        .WithMany()
                        .HasForeignKey("ModerationShopId1");

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopEquipment", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", "ModerationShop")
                        .WithMany("ModerationShopEquipments")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopSchedule", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", "ModerationShop")
                        .WithMany("Schedules")
                        .HasForeignKey("ModerationShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopScheduleInterval", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShopSchedule", "Schedule")
                        .WithMany("Intervals")
                        .HasForeignKey("ModerationShopScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.PhotoMetadata", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Entities.ModerationShop", null)
                        .WithMany("ShopPhotos")
                        .HasForeignKey("ModerationShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShop", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("ModerationCoffeeBeanShops");

                    b.Navigation("ModerationRoasterShops");

                    b.Navigation("ModerationShopBrewMethods");

                    b.Navigation("ModerationShopEquipments");

                    b.Navigation("Schedules");

                    b.Navigation("ShopPhotos");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationShopSchedule", b =>
                {
                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
