// <auto-generated />
using System;
using CoffeePeek.Shops.Infrastructure.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeePeek.Shops.Infrastructure.Migrations
{
    [DbContext(typeof(ShopsDbContext))]
    [Migration("20260107164325_updateLoactionEntity")]
    partial class updateLoactionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.BrewMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BrewMethods");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ShopId", "CreatedAt");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.CoffeeBean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CoffeeBeans");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.CoffeeBeanShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeBeanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeBeanId");

                    b.HasIndex("ShopId");

                    b.ToTable("CoffeeBeanShops");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.FavoriteShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("FavoriteShops");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAddressValidated")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxEvents");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<decimal>("RatingCoffee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RatingPlace")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RatingService")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Roaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roasters");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.RoasterShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoasterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoasterId");

                    b.HasIndex("ShopId");

                    b.ToTable("RoasterShops");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModerationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceRange")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopContactId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ShopContactId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopBrewMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewMethodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrewMethodId");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopBrewMethods");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique();

                    b.ToTable("ShopContacts");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopEquipments");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopPhotos");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopSchedules");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopScheduleInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ShopScheduleIntervals");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("CheckIns")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.CoffeeBeanShop", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.CoffeeBean", "CoffeeBean")
                        .WithMany("CoffeeBeanShops")
                        .HasForeignKey("CoffeeBeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("CoffeeBeanShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeBean");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.FavoriteShop", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Location", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithOne("Location")
                        .HasForeignKey("CoffeePeek.Shops.Domain.Entities.Location", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Review", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("Reviews")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.RoasterShop", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Roaster", "Roaster")
                        .WithMany("RoasterShops")
                        .HasForeignKey("RoasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("RoasterShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roaster");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopBrewMethod", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.BrewMethod", "BrewMethod")
                        .WithMany("ShopBrewMethods")
                        .HasForeignKey("BrewMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopBrewMethods")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrewMethod");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopContact", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithOne("ShopContact")
                        .HasForeignKey("CoffeePeek.Shops.Domain.Entities.ShopContact", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopEquipment", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Equipment", "Equipment")
                        .WithMany("ShopEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopEquipments")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopPhoto", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopPhotos")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopSchedule", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.Shop", "Shop")
                        .WithMany("Schedules")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopScheduleInterval", b =>
                {
                    b.HasOne("CoffeePeek.Shops.Domain.Entities.ShopSchedule", "Schedule")
                        .WithMany("Intervals")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.BrewMethod", b =>
                {
                    b.Navigation("ShopBrewMethods");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.CoffeeBean", b =>
                {
                    b.Navigation("CoffeeBeanShops");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("ShopEquipments");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Roaster", b =>
                {
                    b.Navigation("RoasterShops");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.Shop", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("CoffeeBeanShops");

                    b.Navigation("Location");

                    b.Navigation("Reviews");

                    b.Navigation("RoasterShops");

                    b.Navigation("Schedules");

                    b.Navigation("ShopBrewMethods");

                    b.Navigation("ShopContact");

                    b.Navigation("ShopEquipments");

                    b.Navigation("ShopPhotos");
                });

            modelBuilder.Entity("CoffeePeek.Shops.Domain.Entities.ShopSchedule", b =>
                {
                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
