// <auto-generated />
using System;
using CoffeeShop.Moderation.Persistence.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeShop.Moderation.Persistence.Migrations
{
    [DbContext(typeof(ModerationDbContext))]
    partial class ModerationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationCoffeeBeanShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeBeanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeBeanId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationCoffeeBeanShops");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsSoftDelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModerationShopId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedBy");

                    b.HasIndex("ModerationShopId");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("ModerationReviews");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CoffeeFocus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PriceRange")
                        .HasColumnType("integer");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CoffeeFocus");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("UserId");

                    b.ToTable("ModerationShops");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopBrewMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewMethodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrewMethodId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationShopBrewMethods");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationShopEquipments");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopRoaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoasterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoasterId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationRoasterShops");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ShopImportCandidateAggregate.ShopImportCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CheckDate")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("CoffeeFocus")
                        .HasColumnType("integer");

                    b.Property<int>("CollectorBucket")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuisine")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("GoogleBusinessStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("GoogleFetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleMapsUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("OsmAgeDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OsmUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QueueStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("RejectReason")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResultingShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Signals")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("TagSlugs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeFocus");

                    b.HasIndex("CollectorBucket");

                    b.HasIndex("QueueStatus");

                    b.HasIndex("RejectReason");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("ShopImportCandidates", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ShopImportCandidateAggregate.ShopImportDuplicateSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LeftCandidateId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RightCandidateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Score");

                    b.HasIndex("Status");

                    b.HasIndex("LeftCandidateId", "RightCandidateId")
                        .IsUnique();

                    b.ToTable("ShopImportDuplicateSuggestions", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModeratorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ModerationAuditLogs", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.PhotoMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ModerationReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModerationShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModerationReviewId");

                    b.HasIndex("ModerationShopId");

                    b.ToTable("ShopPhotos");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationCoffeeBeanShop", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationCoffeeBeanShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany()
                        .HasForeignKey("ModerationShopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ModerationReviewId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AverageRating")
                                .HasColumnType("numeric");

                            b1.Property<int>("Coffee")
                                .HasColumnType("integer");

                            b1.Property<int>("Place")
                                .HasColumnType("integer");

                            b1.Property<int>("Service")
                                .HasColumnType("integer");

                            b1.HasKey("ModerationReviewId");

                            b1.ToTable("ModerationReviews");

                            b1.WithOwner()
                                .HasForeignKey("ModerationReviewId");
                        });

                    b.Navigation("ModerationShop");

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", b =>
                {
                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("ModerationShopId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsAddressValidated")
                                .HasColumnType("boolean");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("numeric");

                            b1.HasKey("ModerationShopId");

                            b1.HasIndex("Latitude", "Longitude");

                            b1.ToTable("ModerationShops");

                            b1.WithOwner()
                                .HasForeignKey("ModerationShopId");
                        });

                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraft", "Menu", b1 =>
                        {
                            b1.Property<Guid>("ModerationShopId");

                            b1.Property<DateTime?>("CapturedAtUtc");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("ParseError");

                            b1.Property<int>("ParseStatus");

                            b1.Property<int?>("SuggestedPriceRange");

                            b1.Property<DateTime?>("UpdatedAtUtc");

                            b1.HasKey("ModerationShopId");

                            b1.ToTable("ModerationShops");

                            b1
                                .ToJson("Menu")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ModerationShopId");

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraftItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("MenuDraftModerationShopId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Availability");

                                    b2.Property<int>("Category");

                                    b2.Property<string>("NameEn")
                                        .IsRequired();

                                    b2.Property<string>("NameRu")
                                        .IsRequired();

                                    b2.Property<decimal?>("Price");

                                    b2.Property<string>("Slug")
                                        .IsRequired();

                                    b2.Property<int>("Source");

                                    b2.Property<int?>("VolumeMl");

                                    b2.HasKey("MenuDraftModerationShopId", "__synthesizedOrdinal");

                                    b2.ToTable("ModerationShops");

                                    b2.WithOwner()
                                        .HasForeignKey("MenuDraftModerationShopId");
                                });

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraftPhoto", "Photos", b2 =>
                                {
                                    b2.Property<Guid>("MenuDraftModerationShopId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("ContentType")
                                        .IsRequired();

                                    b2.Property<string>("FileName")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<Guid?>("MediaPhotoId");

                                    b2.Property<long>("SizeBytes");

                                    b2.Property<string>("StorageKey")
                                        .IsRequired();

                                    b2.HasKey("MenuDraftModerationShopId", "__synthesizedOrdinal");

                                    b2.ToTable("ModerationShops");

                                    b2.WithOwner()
                                        .HasForeignKey("MenuDraftModerationShopId");
                                });

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraftUnmatched", "Unmatched", b2 =>
                                {
                                    b2.Property<Guid>("MenuDraftModerationShopId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double?>("Confidence");

                                    b2.Property<decimal?>("Price");

                                    b2.Property<string>("RawName")
                                        .IsRequired();

                                    b2.HasKey("MenuDraftModerationShopId", "__synthesizedOrdinal");

                                    b2.ToTable("ModerationShops");

                                    b2.WithOwner()
                                        .HasForeignKey("MenuDraftModerationShopId");
                                });

                            b1.Navigation("Items");

                            b1.Navigation("Photos");

                            b1.Navigation("Unmatched");
                        });

                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("ModerationShopId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("InstagramLink")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("SiteLink")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.HasKey("ModerationShopId");

                            b1.ToTable("ModerationShops");

                            b1.WithOwner()
                                .HasForeignKey("ModerationShopId");
                        });

                    b.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopSchedule", "Schedules", b1 =>
                        {
                            b1.Property<Guid>("ModerationShopId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("boolean");

                            b1.HasKey("ModerationShopId", "Id");

                            b1.ToTable("ModerationShopSchedule");

                            b1.WithOwner()
                                .HasForeignKey("ModerationShopId");

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopScheduleInterval", "Intervals", b2 =>
                                {
                                    b2.Property<Guid>("ModerationShopScheduleModerationShopId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ModerationShopScheduleId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<TimeSpan>("CloseTime")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("OpenTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("ModerationShopScheduleModerationShopId", "ModerationShopScheduleId", "Id");

                                    b2.ToTable("ModerationShopScheduleInterval");

                                    b2.WithOwner()
                                        .HasForeignKey("ModerationShopScheduleModerationShopId", "ModerationShopScheduleId");
                                });

                            b1.Navigation("Intervals");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopBrewMethod", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationShopBrewMethods")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopEquipment", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationShopEquipments")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopRoaster", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationRoasterShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ShopImportCandidateAggregate.ShopImportCandidate", b =>
                {
                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraft", "Menu", b1 =>
                        {
                            b1.Property<Guid>("ShopImportCandidateId");

                            b1.Property<DateTime?>("CapturedAtUtc");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("ParseError");

                            b1.Property<int>("ParseStatus");

                            b1.Property<int?>("SuggestedPriceRange");

                            b1.Property<DateTime?>("UpdatedAtUtc");

                            b1.HasKey("ShopImportCandidateId");

                            b1.ToTable("ShopImportCandidates");

                            b1
                                .ToJson("Menu")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ShopImportCandidateId");

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraftItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("MenuDraftShopImportCandidateId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Availability");

                                    b2.Property<int>("Category");

                                    b2.Property<string>("NameEn")
                                        .IsRequired();

                                    b2.Property<string>("NameRu")
                                        .IsRequired();

                                    b2.Property<decimal?>("Price");

                                    b2.Property<string>("Slug")
                                        .IsRequired();

                                    b2.Property<int>("Source");

                                    b2.Property<int?>("VolumeMl");

                                    b2.HasKey("MenuDraftShopImportCandidateId", "__synthesizedOrdinal");

                                    b2.ToTable("ShopImportCandidates");

                                    b2.WithOwner()
                                        .HasForeignKey("MenuDraftShopImportCandidateId");
                                });

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraftPhoto", "Photos", b2 =>
                                {
                                    b2.Property<Guid>("MenuDraftShopImportCandidateId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("ContentType")
                                        .IsRequired();

                                    b2.Property<string>("FileName")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<Guid?>("MediaPhotoId");

                                    b2.Property<long>("SizeBytes");

                                    b2.Property<string>("StorageKey")
                                        .IsRequired();

                                    b2.HasKey("MenuDraftShopImportCandidateId", "__synthesizedOrdinal");

                                    b2.ToTable("ShopImportCandidates");

                                    b2.WithOwner()
                                        .HasForeignKey("MenuDraftShopImportCandidateId");
                                });

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.MenuDraftAggregate.MenuDraftUnmatched", "Unmatched", b2 =>
                                {
                                    b2.Property<Guid>("MenuDraftShopImportCandidateId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double?>("Confidence");

                                    b2.Property<decimal?>("Price");

                                    b2.Property<string>("RawName")
                                        .IsRequired();

                                    b2.HasKey("MenuDraftShopImportCandidateId", "__synthesizedOrdinal");

                                    b2.ToTable("ShopImportCandidates");

                                    b2.WithOwner()
                                        .HasForeignKey("MenuDraftShopImportCandidateId");
                                });

                            b1.Navigation("Items");

                            b1.Navigation("Photos");

                            b1.Navigation("Unmatched");
                        });

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.PhotoMetadata", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", null)
                        .WithMany("ReviewPhotos")
                        .HasForeignKey("ModerationReviewId");

                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", null)
                        .WithMany("ShopPhotos")
                        .HasForeignKey("ModerationShopId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", b =>
                {
                    b.Navigation("ReviewPhotos");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", b =>
                {
                    b.Navigation("ModerationCoffeeBeanShops");

                    b.Navigation("ModerationRoasterShops");

                    b.Navigation("ModerationShopBrewMethods");

                    b.Navigation("ModerationShopEquipments");

                    b.Navigation("ShopPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
