// <auto-generated />
using System;
using CoffeeShop.Moderation.Persistence.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeePeek.Moderation.Infrastructure.Migrations
{
    [DbContext(typeof(ModerationDbContext))]
    partial class ModerationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationCoffeeBeanShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeBeanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeBeanId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationCoffeeBeanShops", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationCommunityPostAggregate.ModerationCommunityPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSoftDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PostType")
                        .HasColumnType("integer");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("LinkedShopId");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("UserId");

                    b.ToTable("ModerationCommunityPosts", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsSoftDelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModerationShopId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedBy");

                    b.HasIndex("ModerationShopId");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("ModerationReviews", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PriceRange")
                        .HasColumnType("integer");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("UserId");

                    b.ToTable("ModerationShops", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopBrewMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewMethodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrewMethodId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationShopBrewMethods", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationShopEquipments", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopRoaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoasterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoasterId");

                    b.HasIndex("ShopId");

                    b.ToTable("ModerationRoasterShops", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.ModerationAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModeratorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ModerationAuditLogs", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.PhotoMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ModerationReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModerationShopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModerationReviewId");

                    b.HasIndex("ModerationShopId");

                    b.ToTable("ShopPhotos", (string)null);
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationCoffeeBeanShop", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationCoffeeBeanShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany()
                        .HasForeignKey("ModerationShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ModerationReviewId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AverageRating")
                                .HasColumnType("numeric");

                            b1.Property<int>("Coffee")
                                .HasColumnType("integer");

                            b1.Property<int>("Place")
                                .HasColumnType("integer");

                            b1.Property<int>("Service")
                                .HasColumnType("integer");

                            b1.HasKey("ModerationReviewId");

                            b1.ToTable("ModerationReviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModerationReviewId");
                        });

                    b.Navigation("ModerationShop");

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", b =>
                {
                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("ModerationShopId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("InstagramLink")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("SiteLink")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.HasKey("ModerationShopId");

                            b1.ToTable("ModerationShops", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModerationShopId");
                        });

                    b.OwnsOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("ModerationShopId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsAddressValidated")
                                .HasColumnType("boolean");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("numeric");

                            b1.HasKey("ModerationShopId");

                            b1.HasIndex("Latitude", "Longitude");

                            b1.ToTable("ModerationShops", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModerationShopId");
                        });

                    b.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopSchedule", "Schedules", b1 =>
                        {
                            b1.Property<Guid>("ModerationShopId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("boolean");

                            b1.HasKey("ModerationShopId", "Id");

                            b1.ToTable("ModerationShopSchedule", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModerationShopId");

                            b1.OwnsMany("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopScheduleInterval", "Intervals", b2 =>
                                {
                                    b2.Property<Guid>("ModerationShopScheduleModerationShopId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ModerationShopScheduleId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<TimeSpan>("CloseTime")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("OpenTime")
                                        .HasColumnType("interval");

                                    b2.HasKey("ModerationShopScheduleModerationShopId", "ModerationShopScheduleId", "Id");

                                    b2.ToTable("ModerationShopScheduleInterval", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ModerationShopScheduleModerationShopId", "ModerationShopScheduleId");
                                });

                            b1.Navigation("Intervals");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopBrewMethod", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationShopBrewMethods")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopEquipment", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationShopEquipments")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShopRoaster", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", "ModerationShop")
                        .WithMany("ModerationRoasterShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationShop");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Entities.PhotoMetadata", b =>
                {
                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", null)
                        .WithMany("ReviewPhotos")
                        .HasForeignKey("ModerationReviewId");

                    b.HasOne("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", null)
                        .WithMany("ShopPhotos")
                        .HasForeignKey("ModerationShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationReviewAggregate.ModerationReview", b =>
                {
                    b.Navigation("ReviewPhotos");
                });

            modelBuilder.Entity("CoffeePeek.Moderation.Domain.Aggregates.ModerationShop", b =>
                {
                    b.Navigation("ModerationCoffeeBeanShops");

                    b.Navigation("ModerationRoasterShops");

                    b.Navigation("ModerationShopBrewMethods");

                    b.Navigation("ModerationShopEquipments");

                    b.Navigation("ShopPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
