name: Qodana Configuration Upload

on:
    push:
        branches: [ main, dev, feature ]
    pull_request:
        branches: [ main, dev ]
    workflow_dispatch:
    
jobs:
    qodana:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 'Qodana Scan'
              uses: JetBrains/qodana-action@v2024.3
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_CONFIGURATIONS_TOKEN }}
              with:
                  args: --linter,jetbrains/qodana-dotnet:2024.3
